version: '3.8'

services:
  product-service:
    build: ./product-service
    ports:
      - "8001:8000"
    networks:
      - ecommerce-network
    environment:
      - DATABASE_URL=sqlite:///./products.db

  cart-service:
    build: ./cart-service
    ports:
      - "8002:8000"
    networks:
      - ecommerce-network
    environment:
      - DATABASE_URL=sqlite:///./cart.db

  order-service:
    build: ./order-service
    ports:
      - "8003:8000"
    networks:
      - ecommerce-network
    environment:
      - DATABASE_URL=sqlite:///./orders.db
      - PRODUCT_SERVICE_URL=http://product-service:8000
      - INVENTORY_SERVICE_URL=http://inventory-service:8000
      - PAYMENT_SERVICE_URL=http://payment-service:8000

  user-service:
    build: ./user-service
    ports:
      - "8004:8000"
    networks:
      - ecommerce-network
    environment:
      - DB_CONNECTION=mysql
      - DB_HOST=user-db
      - DB_PORT=3306
      - DB_DATABASE=laravel
      - DB_USERNAME=laravel
      - DB_PASSWORD=secret
    depends_on:
      - user-db

  user-db:
    image: mysql:8.0
    environment:
      - MYSQL_DATABASE=laravel
      - MYSQL_USER=laravel
      - MYSQL_PASSWORD=secret
      - MYSQL_ROOT_PASSWORD=secret
    networks:
      - ecommerce-network
    volumes:
      - user-db-data:/var/lib/mysql

  payment-service:
    build: ./payment-service
    ports:
      - "8005:8000"
    networks:
      - ecommerce-network
    environment:
      - DATABASE_URL=sqlite:///./payments.db

  inventory-service:
    build: ./inventory-service
    ports:
      - "8006:8000"
    networks:
      - ecommerce-network
    environment:
      - DATABASE_URL=sqlite:///./inventory.db

  analytics-service:
    build: ./analytics-service
    ports:
      - "8007:8000"
    networks:
      - ecommerce-network
    environment:
      - DATABASE_URL=sqlite:///./analytics.db

networks:
  ecommerce-network:
    driver: bridge

volumes:
  user-db-data:
